"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowUpLeft, BadgeCheck, Check, ChevronDown, Factory, Fence, Home as HomeIcon, LandPlot, Map, MapPin, Menu, MessageCircle, Search, SlidersHorizontal, Store, Warehouse, X, BriefcaseBusiness, KeyRound, ShieldCheck, Sparkles, UserRound, UsersRound } from "lucide-react";

const PHONE = "971553404293";
const categories = [
  ["سكني", HomeIcon, "/images/IMG_0851.jpeg", "/sharjah/residential"],
  ["مكاتب", BriefcaseBusiness, "/images/105664AE-F9CD-48A0-A9B4-155C62BE1AF0.png", "/sharjah/offices"],
  ["مستودعات", Warehouse, "/images/IMG_8833.png", "/sharjah/warehouses"],
  ["محلات تجارية", Store, "/images/IMG_8830.png", "/sharjah/shops"],
  ["حوطات", Fence, "/images/IMG_8832.png", "/sharjah/yards"],
  ["مزارع", LandPlot, "/images/IMG_8829.png", "/sharjah/farms"],
  ["صناعية مليحة", Factory, "/images/IMG_8835.png", "/sharjah/industrial"],
  ["أراضي للاستثمار", LandPlot, "/images/IMG_8917.jpeg", "/sharjah/land"],
];

const listings = [
  { title:"بناية سكنية جديدة للإيجار في مليحة", area:"مليحة - الشارقة | بالقرب من طريق E102", type:"سكني", size:"11 وحدة سكنية", price:"تواصل لمعرفة السعر", image:"/images/IMG_0851.jpeg", href:"/sharjah/residential/mleiha-building", details:"8 وحدات غرفة وصالة، لكل وحدة مطبخ وحمام منفصلان · 2 استديو · وحدة واحدة غرفتين وصالة ومطبخ وحمام" },
  { title:"مستودع واسع جاهز للاستخدام", area:"الشارقة الصناعية 10", type:"مستودعات", size:"8,500 قدم²", price:"اتصل للسعر", image:"/images/IMG_8910.jpeg" },
  { title:"محل شارع رئيسي بواجهة ممتازة", area:"الشارقة", type:"محلات تجارية", size:"1,250 قدم²", price:"اتصل للسعر", image:"/images/IMG_8911.jpeg" },
  { title:"حوطة مسورة للتخزين والمعدات", area:"الشارقة", type:"حوطات", size:"15,000 قدم²", price:"اتصل للسعر", image:"/images/IMG_8919.jpeg" },
  { title:"مكتب إداري جاهز للشركات", area:"الشارقة", type:"مكاتب", size:"2,100 قدم²", price:"اتصل للسعر", image:"/images/IMG_8916.jpeg" },
  { title:"مزرعة جاهزة للبيع أو الإيجار", area:"الشارقة", type:"مزارع", size:"32,000 قدم²", price:"اتصل للسعر", image:"/images/IMG_8912.jpeg" },
  { title:"سكن منظم واقتصادي", area:"الشارقة", type:"سكني", size:"24 غرفة", price:"اتصل للسعر", image:"/images/IMG_8913.jpeg" },
  { title:"صناعية مليحة الذيد", area:"الشارقة - الذيد", type:"صناعية مليحة", size:"12,000 قدم²", price:"اتصل للسعر", image:"/images/IMG_8968.jpeg" },
  { title:"أرض استثمارية جاهزة", area:"الشارقة", type:"أراضي للاستثمار", size:"32,000 قدم²", price:"اتصل للسعر", image:"/images/D58F403E-6FCC-482D-83E1-2759AC020532.png" }
];

const faq = [
  ["هل كل العقارات من المالك مباشرة؟","الهوية الأساسية للمنصة مبنية على العقارات المباشرة من المالك، ويمكن لاحقًا إضافة وسطاء في قسم منفصل إذا رغبت."],
  ["كيف يضيف المالك عقاره؟","من خلال نموذج واضح يرسل الفئة والموقع والمساحة والسعر والصور وبيانات التواصل، ثم يمر الإعلان بالمراجعة قبل النشر."],
  ["هل يمكن تمييز العقارات الموثقة؟","نعم، يوجد شارة توثيق يمكن منحها بعد مراجعة بيانات المالك والعقار."],
  ["هل يمكن فتح حساب لكل مالك؟","نعم، في المرحلة التالية يمكن إضافة تسجيل دخول ولوحة لكل مالك لإدارة عقاراته واستفساراته."]
];

export default function Home() {
  const [menu,setMenu]=useState(false); const [activeCat,setActiveCat]=useState("الكل"); const [purpose,setPurpose]=useState("إيجار"); const [faqOpen,setFaqOpen]=useState(0); const [submitted,setSubmitted]=useState(false);
  const visible=useMemo(()=>activeCat==="الكل"?listings:listings.filter(x=>x.type===activeCat),[activeCat]);
  return <main>
    <header className="nav shell"><a className="brand" href="#top">من المالك <span>مباشرة</span></a><nav className="navlinks"><a href="#properties">العقارات</a><a href="#categories">الفئات</a><a href="#owners">أضف عقارك</a><a href="#how">كيف تعمل</a></nav><div className="navActions"><a className="plain" href="#properties"><Search size={17}/> بحث</a><a className="pill dark" href="#owners">اعرض عقارك</a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    {menu&&<div className="mobileMenu"><a href="#properties" onClick={()=>setMenu(false)}>العقارات</a><a href="#categories" onClick={()=>setMenu(false)}>الفئات</a><a href="#owners" onClick={()=>setMenu(false)}>أضف عقارك</a><a href="#how" onClick={()=>setMenu(false)}>كيف تعمل</a></div>}
    <section className="hero shell" id="top"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> بدون تعقيد — تواصل مباشر مع المالك</div><h1>هلوفيرا للعقارات.<br/><em>من المالك مباشرة.</em></h1><p>منصة إيجار وبيع الصناعيات، المحلات التجارية، المكاتب، المستودعات، السكني، الحوطات، المزارع والأراضي الاستثمارية في الإمارات، مع تواصل مباشر وبيانات واضحة.</p><div className="searchPanel"><div className="segmented">{["إيجار","بيع"].map(x=><button key={x} className={purpose===x?"active":""} onClick={()=>setPurpose(x)}>{x}</button>)}</div><div className="searchGrid"><label><span>نوع العقار</span><select value={activeCat} onChange={e=>setActiveCat(e.target.value)}><option>الكل</option>{categories.map(([n])=><option key={n}>{n}</option>)}</select></label><label><span>الإمارة</span><select><option>كل الإمارات</option><option>دبي</option><option>أبوظبي</option><option>الشارقة</option><option>عجمان</option><option>رأس الخيمة</option><option>الفجيرة</option><option>أم القيوين</option></select></label><label><span>المساحة</span><select><option>أي مساحة</option><option>أقل من 2,000 قدم²</option><option>2,000 - 5,000 قدم²</option><option>5,000 - 10,000 قدم²</option><option>أكثر من 10,000 قدم²</option></select></label><a className="searchBtn" href="#properties"><Search size={20}/> ابحث الآن</a></div></div><div className="trustRow"><span><BadgeCheck size={16}/> عقارات مباشرة</span><span><ShieldCheck size={16}/> مراجعة قبل النشر</span><span><MessageCircle size={16}/> واتساب مباشر</span></div></div><div className="heroVisual"><img src="/images/105664AE-F9CD-48A0-A9B4-155C62BE1AF0.png" alt="فريق هلوفيرا للعقارات" style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:"32px"}}/></div></section>
    <section className="shell" style={{marginTop:"24px",marginBottom:"24px"}}><img src="/images/D0D5804C-1764-45C6-A42E-E96388DF61EB.png" alt="مالك مباشر" style={{width:"100%",display:"block",borderRadius:"32px"}}/></section>
    <section className="metrics"><div className="shell metricGrid"><div><strong>8</strong><span>فئات رئيسية</span></div><div><strong>7</strong><span>إمارات</span></div><div><strong>Direct</strong><span>من المالك</span></div><div><strong>24/7</strong><span>استقبال طلبات</span></div></div></section>
    <section className="categories shell" id="categories"><div className="sectionHead"><span className="kicker">01 — الفئات</span><h2>خطوتك نحو العقار المناسب تبدأ من هنا.</h2></div><div className="catGrid">{categories.map(([name,Icon,image,href],i)=><button key={name} className={`catCard ${activeCat===name?"selected":""}`} style={{position:"relative"}} onClick={()=>window.location.href=href}><img className="catImage" src={image} alt={name}/><span className="num">{String(i+1).padStart(2,"0")}</span><div className="catIcon"><Icon size={25}/></div><div style={{position:"absolute",bottom:0,left:0,right:0,height:"46px",background:"white",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 14px",boxSizing:"border-box"}}><span style={{color:"#0a8cff",fontSize:"15px",fontWeight:"700"}}>{name}</span><ArrowUpLeft size={14} color="#0a8cff"/></div></button>)}</div></section>
    <section className="properties shell" id="properties"><div className="sectionHead row"><div><span className="kicker">02 — العقارات</span><h2>عروض من المالك مباشرة.</h2></div><div className="filters"><button><SlidersHorizontal size={16}/> فلترة</button><button><Map size={16}/> الخريطة</button></div></div><div className="categoryTabs"><button className={activeCat==="الكل"?"active":""} onClick={()=>setActiveCat("الكل")}>الكل</button>{categories.map(([n])=><button key={n} className={activeCat===n?"active":""} onClick={()=>setActiveCat(n)}>{n}</button>)}</div><div className="listingGrid">{visible.map((item,i)=><article className="listing" key={item.title}><div className={`propertyArt art${i%6}`}><img src={item.image} alt={item.title} style={{width:"100%",height:"100%",objectFit:"cover"}}/><span className="status">متاح</span><span className="direct"><UserRound size={13}/>مالك مباشر</span></div><div className="listingBody"><div className="meta"><span><MapPin size={14}/>{item.area}</span><span>{item.size}</span></div><h3>{item.title}</h3>{item.details&&<p style={{margin:"8px 0",fontSize:"14px",lineHeight:1.8}}>{item.details}</p>}<strong>{item.price}</strong><div className="listingActions"><a href={item.href||"#contact"}>التفاصيل <ArrowLeft size={16}/></a><a className="whatsMini" href={`https://wa.me/${PHONE}`}><MessageCircle size={16}/> تواصل مع المالك</a></div></div></article>)}</div></section>
    <section className="owners" id="owners"><div className="shell ownerGrid"><div><span className="kicker light">03 — للمالك</span><h2>اعرض عقارك بنفسك.</h2><p>أرسل بيانات العقار، ونحن نجهز الإعلان ونراجعه قبل ظهوره.</p><div className="ownerSteps"><span><b>1</b> أرسل البيانات</span><span><b>2</b> نراجع العقار</span><span><b>3</b> ينشر كـ “مالك مباشر”</span></div></div><form className="ownerForm" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;const message=`طلب إضافة عقار جديد\n\nاسم المالك: ${f.elements[0].value}\nرقم الهاتف: ${f.elements[1].value}\nنوع العقار: ${f.elements[2].value}\nالإمارة: ${f.elements[3].value}\nالمساحة: ${f.elements[4].value}\nالسعر: ${f.elements[5].value}\nالوصف: ${f.elements[6].value}`;window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(message)}`,"_blank");setSubmitted(true)}}><h3>إضافة عقار</h3><div className="formGrid"><label>اسم المالك<input required placeholder="الاسم الكامل"/></label><label>رقم الهاتف<input required placeholder="+971"/></label><label>نوع العقار<select>{categories.map(([n])=><option key={n}>{n}</option>)}</select></label><label>الإمارة<select><option>الشارقة</option><option>دبي</option><option>أبوظبي</option><option>عجمان</option><option>رأس الخيمة</option><option>الفجيرة</option><option>أم القيوين</option></select></label><label>المساحة<input placeholder="مثال: 5000 قدم²"/></label><label>السعر<input placeholder="السعر المطلوب"/></label></div><label>وصف مختصر<textarea placeholder="الموقع، الاستخدام، المميزات..."/></label><button className="submitBtn" type="submit">إرسال الطلب عبر واتساب <ArrowLeft size={17}/></button>{submitted&&<p className="success"><Check size={16}/> تم تجهيز الطلب وفتح واتساب للإرسال.</p>}</form></div></section>
    <section className="how shell" id="how"><div className="sectionHead"><span className="kicker">04 — كيف تعمل</span><h2>أقصر طريق بين العقار والمستأجر.</h2></div><div className="steps"><div><b>01</b><Search/><h3>ابحث</h3><p>اختر الفئة والإمارة والمساحة.</p></div><div><b>02</b><BadgeCheck/><h3>راجع</h3><p>شاهد البيانات والصور وحالة التوثيق.</p></div><div><b>03</b><MessageCircle/><h3>تواصل</h3><p>اتصل بالمالك أو راسله مباشرة.</p></div></div></section>
    <section className="faq shell"><div className="sectionHead"><span className="kicker">05 — أسئلة شائعة</span><h2>واضح من البداية.</h2></div><div className="faqList">{faq.map(([q,a],i)=><button key={q} className="faqItem" onClick={()=>setFaqOpen(faqOpen===i?-1:i)}><span>{q}<ChevronDown size={18}/></span>{faqOpen===i&&<p>{a}</p>}</button>)}</div></section>
    <section className="cta shell"><div><span>لديك عقار؟</span><h2>ضعه أمام العميل المناسب.</h2></div><a href="#owners">أضف عقارك الآن <ArrowLeft/></a></section>
    <footer id="contact"><div className="shell footerGrid"><div><a className="brand lightBrand" href="#top">من المالك <span>مباشرة</span></a><p>منصة عقارات مباشرة في الإمارات.</p></div><div><h4>الفئات</h4>{categories.slice(0,5).map(([n])=><a href="#categories" key={n}>{n}</a>)}</div><div><h4>روابط</h4><a href="#properties">العقارات</a><a href="#owners">أضف عقارك</a><a href="#how">كيف تعمل</a></div><div><h4>تواصل</h4><a href={`https://wa.me/${PHONE}`}>واتساب</a><a href={`tel:+${PHONE}`}>اتصال مباشر</a><a href="mailto:hello@haloveraproperties.com">hello@haloveraproperties.com</a></div></div><div className="shell copyright">© 2026 Halovera Properties — من المالك مباشرة</div></footer>
    <a className="floatingWhats" href={`https://wa.me/${PHONE}`} aria-label="واتساب"><MessageCircle/></a>
  </main>
}